export default {
REGISTER_VEHICLE : "REGISTER_VEHICLE",
GET_VEHICLES : "GET_VEHICLES",
GET_VEHICLES_SUCCESS: "GET_VEHICLES_SUCCESS",
TRANSPORTER_BOOKINGS: "TRANSPORTER_BOOKINGS",
TRANSPORTER_BOOKINGS_SUCCESS: "TRANSPORTER_BOOKINGS_SUCCESS",
DELETE_VEHICLE: "DELETE_VEHICLE",
UPDATE_BOOKING_STATUS: "UPDATE_BOOKING_STATUS",
MAKE_VEHICLE_AVAILABLE: "MAKE_VEHICLE_AVAILABLE",
REJECT_VEHICLE_BOOKING: "REJECT_VEHICLE_BOOKING",
RELEASE_VEHICLE: "RELEASE_VEHICLE",
UPDATE_VEHICLE: "UPDATE_VEHICLE",
UPDATE_PROFILE: "UPDATE_PROFILE",
}